---
Wallets:
  -
    Accounts:
      -
        Addresses:
          - DdzFFzCqrhsrM9GN7kvQgBNNA4AkzgXN6FFdYsPFd9ftf4ghDf9AkqU4CxJSUbtWFnx1nnBsdwTmrXZ7PmfDV1t2nVxXaEarYNMWZLSN
          - DdzFFzCqrhsrM9GN7kvQgBNNA4AkzgXN6FFdYsPFd9ftf4ghDf9AkqU4CxJSUbtWFnx1nnBsdwTmrXZ7PmfDV1t2nVxXaEarYNMWZLSN
          - DdzFFzCqrhsrM9GN7kvQgBNNA4AkzgXN6FFdYsPFd9ftf4ghDf9AkqU4CxJSUbtWFnx1nnBsdwTmrXZ7PmfDV1t2nVxXaEarYNMWZLSN
          - DdzFFzCqrhsrM9GN7kvQgBNNA4AkzgXN6FFdYsPFd9ftf4ghDf9AkqU4CxJSUbtWFnx1nnBsdwTmrXZ7PmfDV1t2nVxXaEarYNMWZLSN
        AccountId: Ae2tdPwUPEZD7r1mGc4BxGj5ikBop9DpdsKDzKpFujdYpd6bZBn9fZYEgsg
      -
        Addresses:
          - DdzFFzCqrhsrM9GN7kvQgBNNA4AkzgXN6FFdYsPFd9ftf4ghDf9AkqU4CxJSUbtWFnx1nnBsdwTmrXZ7PmfDV1t2nVxXaEarYNMWZLSN
          - DdzFFzCqrhsrM9GN7kvQgBNNA4AkzgXN6FFdYsPFd9ftf4ghDf9AkqU4CxJSUbtWFnx1nnBsdwTmrXZ7PmfDV1t2nVxXaEarYNMWZLSN
        AccountId: Ae2tdPwUPEZD7r1mGc4BxGj5ikBop9DpdsKDzKpFujdYpd6bZBn9fZYEgsg
    WalletId: Ae2tdPwUPEZD7r1mGc4BxGj5ikBop9DpdsKDzKpFujdYpd6bZBn9fZYEgsg
  -
    Accounts:
      -
        Addresses:
          - DdzFFzCqrhsrM9GN7kvQgBNNA4AkzgXN6FFdYsPFd9ftf4ghDf9AkqU4CxJSUbtWFnx1nnBsdwTmrXZ7PmfDV1t2nVxXaEarYNMWZLSN
        AccountId: Ae2tdPwUPEZD7r1mGc4BxGj5ikBop9DpdsKDzKpFujdYpd6bZBn9fZYEgsg
    WalletId: Ae2tdPwUPEZD7r1mGc4BxGj5ikBop9DpdsKDzKpFujdYpd6bZBn9fZYEgsg
